# 基本服务配置
server:
  port: 8099 # 端口配置
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://192.168.101.101:3306/nginx?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # 最大连接池大小
      minimum-idle: 5 # 最小空闲连接数
      pool-name: HikariCP # 连接池名称
      idle-timeout: 30000 # 空闲连接超时时间（毫秒）
      connection-timeout: 30000 # 获取连接的超时时间（毫秒）
  web:
    resources:
      static-locations: file:./chart_images/ # 静态资源路径

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
    com.baomidou.mybatisplus.core.mapper: DEBUG
    com.baomidou.mybatisplus.extension.plugins: DEBUG

ali:
  appcode: # 这里使用您自己的 AppCode
  url: https://ipaddquery.market.alicloudapi.com/ip/address-query



